name: GitHub Actions
on: [create, push]
jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
    - name: Install Python dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pip install pipenv
        pipenv sync --dev
    - name: Run Tests
      run: make test
  cd:
    name: Continuous delivery
    runs-on: ubuntu-latest
    needs: ci
    if: |
      github.event_name == 'create' && github.event.ref_type == 'tag' ||
      (github.event_name == 'push' && endsWith(github.event.ref, '/master'))
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
